### ISSUE TITLE
Twister UI and Twister OS Armbian Support

### ISSUE THREAD

**Issue by FlameKat53** [Botspot/TwistUP#2]
It would be very nice to have the better Twister OS Patcher on Twister UI (and Twister OS Armbian) instead of being stuck with FlameKat53's (hey that's me!) patcher :yum:

**Comment by Botspot** [comment]
What changes would need to be made to TwistUP for it to become the Twist UI patcher?

**Comment by Itai-Nelken** [comment]
> What changes would need to be made to TwistUP for it to become the Twist UI patcher?

I guess just changing the download from TwisterOS patches to TwisterUI patches.

**Comment by Botspot** [comment]
> > What changes would need to be made to TwistUP for it to become the Twist UI patcher?
> 
> I guess just changing the download from TwisterOS patches to TwisterUI patches.

We've been going round and round about that. So far nobody has told me **what URLs** are being used.

**Comment by Itai-Nelken** [comment]
https://twisteros.com/Patches/latestui.txt
https://twisteros.com/Patches/TwisterUIv***.run

@Botspot I think does are the links
here is the GitHub repo for the current TwisterUI patcher: https://github.com/FlameKat53/Twister-UI-Patcher

**Comment by FlameKat53** [comment]
we need to make new URLs and get @phoenixbyrd to push them to github, one for twister UI and one for Twister OS Armbian

**Comment by NoozAbooz** [comment]
This ticket oldddd lol

**Comment by Botspot** [comment]
Phoenixbyrd made these changes in [his fork](https://github.com/phoenixbyrd/TwistUP-OS), so this issue can be closed.
